import { notificationBudgetDecision } from './one-to-one.ts';

type DbLike={from:(table:string)=>any};
export type NotificationGuardInput={memberId:string;module:string;category:string;priority:'critical'|'action_required'|'reminder'|'informational';actionComplete?:boolean;now?:Date};
export type NotificationGuardResult={allowed:boolean;reason:string;monthlyUsed:number;monthlyQuota:number;dailyCount:number;weeklyReminderCount:number;hoursSinceLast:number;quietHours:boolean;budgetPct:number};

function bangkokParts(now:Date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(now);const get=(type:string)=>parts.find(x=>x.type===type)?.value||'';return{date:`${get('year')}-${get('month')}-${get('day')}`,month:`${get('year')}-${get('month')}`,hour:Number(get('hour'))};}

export async function evaluateNotificationGuard(db:DbLike,input:NotificationGuardInput):Promise<NotificationGuardResult>{
  const now=input.now||new Date(),parts=bangkokParts(now),dayStart=new Date(`${parts.date}T00:00:00+07:00`),monthStart=new Date(`${parts.month}-01T00:00:00+07:00`),weekStart=new Date(dayStart);weekStart.setUTCDate(weekStart.getUTCDate()-((weekStart.getUTCDay()+6)%7));
  const [{data:budgets},{data:settings},{data:contact},{data:mute},{count:globalMonthlyUsed},{count:moduleMonthlyUsed},{count:dailyCount},{count:weeklyReminderCount},{data:lastDelivery},{count:duplicateCount}]=await Promise.all([
    db.from('notification_budget_config').select('*').in('module',['global',input.module]),
    db.from('settings').select('key,value').in('key',['ONE_TO_ONE_EMERGENCY_STOP','ONE_TO_ONE_PILOT_MEMBER_IDS','FEATURE_ONE_TO_ONE_SYSTEM']),
    db.from('member_contact_preferences').select('reminders_paused_until').eq('member_id',input.memberId).maybeSingle(),
    db.from('line_notif_settings').select('is_muted').eq('member_id',input.memberId).in('notif_type',[input.category,'all']).eq('is_muted',true).limit(1).maybeSingle(),
    db.from('line_message_deliveries').select('id',{count:'exact',head:true}).eq('status','sent').gte('sent_at',monthStart.toISOString()),
    db.from('line_message_deliveries').select('id',{count:'exact',head:true}).eq('status','sent').eq('module',input.module).gte('sent_at',monthStart.toISOString()),
    db.from('line_message_deliveries').select('id',{count:'exact',head:true}).eq('member_id',input.memberId).eq('status','sent').gte('sent_at',dayStart.toISOString()),
    db.from('line_message_deliveries').select('id',{count:'exact',head:true}).eq('member_id',input.memberId).eq('status','sent').ilike('notification_type','%reminder%').gte('sent_at',weekStart.toISOString()),
    db.from('line_message_deliveries').select('sent_at').eq('member_id',input.memberId).eq('status','sent').order('sent_at',{ascending:false}).limit(1).maybeSingle(),
    db.from('line_message_deliveries').select('id',{count:'exact',head:true}).eq('member_id',input.memberId).eq('notification_type',input.category).eq('status','sent').gte('sent_at',weekStart.toISOString()),
  ]);
  const setting=new Map(((settings||[]) as Record<string,unknown>[]).map(x=>[String(x.key),String(x.value)]));const emergency=setting.get('ONE_TO_ONE_EMERGENCY_STOP')==='true';let pilotIds:string[]=[];try{pilotIds=JSON.parse(setting.get('ONE_TO_ONE_PILOT_MEMBER_IDS')||'[]');}catch{pilotIds=[];}const feature=setting.get('FEATURE_ONE_TO_ONE_SYSTEM')==='true';
  const rows=(budgets||[]) as Record<string,unknown>[],global=rows.find(x=>x.module==='global')||{},moduleBudget=rows.find(x=>x.module===input.module)||{};const quota=Number(moduleBudget.monthly_hard_cap||3000),globalQuota=Number(global.monthly_hard_cap||15000),used=Number(moduleMonthlyUsed||0),globalUsed=Number(globalMonthlyUsed||0),lastAt=String((lastDelivery as Record<string,unknown>|null)?.sent_at||''),hoursSinceLast=lastAt?(now.getTime()-new Date(lastAt).getTime())/3600000:999,quiet=parts.hour>=20||parts.hour<8;
  let forcedReason='';if(input.module==='one_to_one'&&emergency)forcedReason='emergency_stop';else if(input.module==='one_to_one'&&!feature&&!pilotIds.includes(input.memberId))forcedReason='outside_pilot';else if((contact as Record<string,unknown>|null)?.reminders_paused_until&&new Date(String((contact as Record<string,unknown>).reminders_paused_until))>now)forcedReason='member_snoozed';else if(mute)forcedReason='member_muted';
  const base={priority:input.priority,dailyCount:Number(dailyCount||0),weeklyReminderCount:Number(weeklyReminderCount||0),hoursSinceLast,quietHours:quiet,duplicate:Number(duplicateCount||0)>0,actionComplete:Boolean(input.actionComplete)},moduleDecision=notificationBudgetDecision({...base,monthlyUsed:used,monthlyQuota:quota}),globalDecision=notificationBudgetDecision({...base,monthlyUsed:globalUsed,monthlyQuota:globalQuota});const decision=!moduleDecision.allowed?moduleDecision:globalDecision,reason=forcedReason||decision.reason;return{allowed:!forcedReason&&decision.allowed,reason,monthlyUsed:used,monthlyQuota:quota,dailyCount:Number(dailyCount||0),weeklyReminderCount:Number(weeklyReminderCount||0),hoursSinceLast,quietHours:quiet,budgetPct:quota?Math.round(used/quota*100):100};
}

export async function logSuppressedNotification(db:any,input:NotificationGuardInput,guard:NotificationGuardResult,idempotencyKey:string,recipientId:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${idempotencyKey}:${guard.reason}`));const payloadHash=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');await db.from('line_message_deliveries').upsert({idempotency_key:`suppressed:${idempotencyKey}:${guard.reason}`,channel:'push',recipient_id:recipientId,member_id:input.memberId,notification_type:input.category,source:input.module,payload_hash:payloadHash,status:'skipped',module:input.module,category:input.category,priority:input.priority,suppression_reason:guard.reason,estimated_count:1},{onConflict:'idempotency_key',ignoreDuplicates:true});}
