import { generateHandshakeCode, handshakeCodeHash, notificationBudgetDecision, oneToOneGoogleCalendarUrl, oneToOneIcs, pairStatusFromVerification, safeHashEqual } from './one-to-one.ts';

Deno.test('ICS มีเวลา 45 นาที stable UID และ reminder 24h/1h',()=>{const out=oneToOneIcs({uid:'pair-1@bni-ideal',partnerName:'สมชาย',startsAt:'2026-08-25T03:00:00.000Z'});for(const value of ['UID:pair-1@bni-ideal','DTSTART:20260825T030000Z','DTEND:20260825T034500Z','TRIGGER:-P1D','TRIGGER:-PT1H'])if(!out.includes(value))throw new Error(`missing ${value}`);});
Deno.test('Google Calendar URL มีชื่อและเวลา',()=>{const url=oneToOneGoogleCalendarUrl({uid:'x',partnerName:'สมหญิง',startsAt:'2026-08-25T03:00:00Z'});if(!url.startsWith('https://calendar.google.com/calendar/render?')||!decodeURIComponent(url).includes('สมหญิง'))throw new Error('invalid calendar url');});
Deno.test('budget ปิด informational ที่ 75% และหยุดเมื่อ action สำเร็จ',()=>{const base={monthlyUsed:750,monthlyQuota:1000,priority:'informational' as const,dailyCount:0,weeklyReminderCount:0,hoursSinceLast:30,quietHours:false,duplicate:false,actionComplete:false};if(notificationBudgetDecision(base).allowed)throw new Error('must suppress');if(notificationBudgetDecision({...base,monthlyUsed:0,actionComplete:true}).reason!=='action_completed')throw new Error('must stop after action');});
Deno.test('critical ผ่าน quiet hours ถ้ายังไม่ถึง approval threshold',()=>{const out=notificationBudgetDecision({monthlyUsed:10,monthlyQuota:1000,priority:'critical',dailyCount:3,weeklyReminderCount:5,hoursSinceLast:1,quietHours:true,duplicate:false,actionComplete:false});if(!out.allowed)throw new Error(out.reason);});
Deno.test('Handshake สร้างรหัสหกหลักและ hash ผูกกับ pair/member',async()=>{const code=generateHandshakeCode(new Uint32Array([42]));if(code!=='000042')throw new Error(code);const a=await handshakeCodeHash('p1','m1',code,'pepper'),b=await handshakeCodeHash('p1','m2',code,'pepper');if(a===b||!safeHashEqual(a,a)||safeHashEqual(a,b))throw new Error('hash binding failed');});
Deno.test('ใช้รหัสตนเองแทนรหัสคู่ไม่ได้',async()=>{const own=await handshakeCodeHash('p1','m1','123456','pepper');const submittedAsPartner=await handshakeCodeHash('p1','m2','123456','pepper');if(safeHashEqual(own,submittedAsPartner))throw new Error('own code accepted');});
Deno.test('Verification status ต้องครบสองฝ่ายและติดป้าย late',()=>{if(pairStatusFromVerification(true,false,'2099-01-01T00:00:00Z')!=='partially_verified')throw new Error('partial');if(pairStatusFromVerification(true,true,'2020-01-01T00:00:00Z')!=='late_verified')throw new Error('late');if(pairStatusFromVerification(true,true,'2099-01-01T00:00:00Z')!=='verified')throw new Error('verified');});
