import { requireAuth } from '../../_shared/auth.ts';
import { getServiceClient, jsonResponse, errResponse } from '../../_shared/db.ts';
import { generateHandshakeCode, handshakeCodeHash } from '../../_shared/one-to-one.ts';
import { linePush, linePushMessages } from '../../_shared/line.ts';
import { evaluateNotificationGuard, logSuppressedNotification } from '../../_shared/notification-orchestrator.ts';
import { derivePairNextAction, pairStatusAfterContact } from '../../_shared/one-to-one-pair-action.ts';
import { member121ProfileCompleteness } from '../../_shared/member-121-profile.ts';

const ROLES=['mc','toomtam','aof','draft','phai','amp','mentor_support'];
const activeStatuses=['matched','contacted','scheduled','confirmed_schedule','awaiting_verification','partially_verified','overdue','unable_to_contact','missed_appointment'];

export async function handleMentor121(p:Record<string,unknown>):Promise<Response>{
  const db=getServiceClient(),action=String(p.action||'');const auth=await requireAuth(db,p,ROLES);if(!auth.ok)return errResponse(auth.error||'ไม่มีสิทธิ์',403);const team=String(auth.teamName||''),isSupport=auth.role==='mentor_support';
  const inScope=(member:Record<string,unknown>|null|undefined)=>Boolean(auth.isMC)||isSupport||(Boolean(team)&&String(member?.mentor_team||'').toLowerCase()===team.toLowerCase());
  const supportBlockedActions=new Set(['updateOneToOnePairOperation','updateOneToOneScheduleOperation','updateOneToOneReferralOutcome','retryOneToOneDelivery','remindMentorOneToOneMember','reissueMentorOneToOneCode']);
  if(isSupport&&supportBlockedActions.has(action))return errResponse('Mentor Support ช่วยตรวจข้อมูลและตอบในคิวภายในได้ แต่การติดต่อหรือเปลี่ยนขั้นตอนของสมาชิกต้องให้ Mentor Co. หรือ Mentor หลักของทีมดำเนินการ',403);

  if(action==='getOneToOnePairAction'){
    const pairId=String(p.pairId||'');
    const {data:pair}=await db.from('matching_pairs').select('id,round_id,status,created_at,member_a_id,member_b_id,member_a:members!matching_pairs_member_a_id_fkey(id,name,nickname,profession,company_name,mentor_team),member_b:members!matching_pairs_member_b_id_fkey(id,name,nickname,profession,company_name,mentor_team),round:matching_rounds(meeting_date,ends_at)').eq('id',pairId).is('archived_at',null).maybeSingle();
    const row=pair as Record<string,unknown>|null;if(!row||(!inScope(row.member_a as Record<string,unknown>)&&!inScope(row.member_b as Record<string,unknown>)))return errResponse('ไม่พบคู่ในขอบเขตที่คุณดูแล',403);
    const ids=[String(row.member_a_id),String(row.member_b_id)];
    const [{data:deliveries},{data:schedules},{data:verifications},{data:guided},{data:feedback},{data:followups},{data:attention},{data:events},{data:questions}]=await Promise.all([
      db.from('line_message_deliveries').select('id,member_id,status,notification_type,sent_at,created_at,suppression_reason,last_error').eq('matching_pair_id',pairId).eq('module','one_to_one').order('created_at',{ascending:false}).limit(50),
      db.from('one_to_one_schedules').select('id,starts_at,status,proposed_by,confirmed_by_a_at,confirmed_by_b_at,updated_at').eq('pair_id',pairId).order('updated_at',{ascending:false}).limit(5),
      db.from('one_to_one_verifications').select('member_id,flow_started_at,verified_partner_code_at,code_expires_at').eq('pair_id',pairId),
      db.from('guided_one_to_one_sessions').select('id,session_mode,status,current_step,current_speaker_member_id,started_at,paused_at,completed_at,duration_seconds,updated_at').eq('pair_id',pairId).order('updated_at',{ascending:false}).limit(1),
      db.from('one_to_one_feedback').select('id,respondent_member_id,visibility,mentor_help,created_at').eq('pair_id',pairId).is('archived_at',null),
      db.from('one_to_one_follow_up_actions').select('id,owner_member_id,related_member_id,action_type,description,due_date,status,created_at').eq('pair_id',pairId).order('created_at',{ascending:false}),
      db.from('one_to_one_attention_items').select('id,member_id,level,reason,suggested_action,status,due_date,created_at').eq('pair_id',pairId).order('created_at',{ascending:false}),
      db.from('one_to_one_status_events').select('id,member_id,event_type,actor_type,created_at').eq('pair_id',pairId).order('created_at',{ascending:false}).limit(80),
      db.from('one_to_one_premeeting_questions').select('id,asked_by_member_id,for_member_id,status,created_at').eq('pair_id',pairId).is('archived_at',null),
    ]);
    const ds=(deliveries||[]) as Record<string,unknown>[],latestDelivery=ids.map(memberId=>ds.find(d=>String(d.member_id)===memberId&&String(d.status)==='sent')).filter(Boolean) as Record<string,unknown>[];
    const ss=(schedules||[]) as Record<string,unknown>[],gs=((guided||[]) as Record<string,unknown>[])[0]||null,fb=(feedback||[]) as Record<string,unknown>[],fu=(followups||[]) as Record<string,unknown>[],at=(attention||[]) as Record<string,unknown>[];
    const sharedIds=[...new Set(fb.filter(x=>String(x.visibility)==='shared').map(x=>String(x.respondent_member_id)))];
    const openHelp=fb.filter(x=>String(x.visibility)==='private_mentor'&&Boolean(x.mentor_help)).length+at.filter(x=>['open','reviewed','snoozed'].includes(String(x.status))&&String(x.reason).includes('mentor')).length;
    const nextAction=derivePairNextAction({participantIds:ids,deliveredMemberIds:latestDelivery.map(x=>String(x.member_id)),scheduleStatus:String(ss[0]?.status||''),guidedStatus:String(gs?.status||''),pairStatus:String(row.status),sharedReflectionMemberIds:sharedIds,openFollowUps:fu.filter(x=>['pending','in_progress','overdue'].includes(String(x.status))).length,openMentorHelp:openHelp});
    return jsonResponse({ok:true,pair:row,deliveries:ds,schedules:ss,verifications:verifications||[],guided:gs,feedbackSummary:{sharedMemberIds:sharedIds,mentorHelpCount:openHelp},followUps:fu,attention:at,events:events||[],preMeetingQuestionCount:(questions||[]).length,nextAction,permission:{canManage:true,scope:auth.isMC?'chapter':'mentor_team'}});
  }

  if(action==='updateOneToOnePairOperation'){
    const pairId=String(p.pairId||''),operation=String(p.operation||''),reason=String(p.reason||'').trim().slice(0,500),ownerRole=String(p.ownerRole||auth.role).trim().slice(0,40);
    const {data:pair}=await db.from('matching_pairs').select('id,round_id,status,member_a_id,member_b_id,member_a:members!matching_pairs_member_a_id_fkey(id,mentor_team),member_b:members!matching_pairs_member_b_id_fkey(id,mentor_team)').eq('id',pairId).is('archived_at',null).maybeSingle();const row=pair as Record<string,unknown>|null;
    if(!row||(!inScope(row.member_a as Record<string,unknown>)&&!inScope(row.member_b as Record<string,unknown>)))return errResponse('ไม่พบคู่ในขอบเขตที่คุณดูแล',403);
    const changes:Record<string,unknown>={};let eventType='pair_operation_updated';
    if(operation==='contacted'){const nextStatus=pairStatusAfterContact(String(row.status));if(nextStatus!==String(row.status))changes.status=nextStatus;changes.last_contacted_at=new Date().toISOString();changes.last_contacted_by=String(auth.role);eventType='pair_contacted';}
    else if(operation==='unable_to_contact'){changes.status='unable_to_contact';changes.last_contacted_at=new Date().toISOString();changes.last_contacted_by=String(auth.role);eventType='pair_unable_to_contact';}
    else if(operation==='assign'){changes.care_owner_role=ownerRole;eventType='pair_care_assigned';}
    else if(operation==='snooze'){const until=new Date(String(p.snoozedUntil||''));if(!Number.isFinite(until.getTime())||until<=new Date())return errResponse('กรุณาเลือกเวลาติดตามที่อยู่ในอนาคต');changes.care_snoozed_until=until.toISOString();eventType='pair_care_snoozed';}
    else if(operation==='cancel'){if(!auth.isMC)return errResponse('เฉพาะ MC ที่ยกเลิกคู่ได้',403);if(!reason)return errResponse('กรุณาระบุเหตุผลยกเลิก');changes.status='cancelled';changes.cancellation_reason=reason;changes.archived_at=new Date().toISOString();eventType='pair_cancelled';}
    else return errResponse('คำสั่งจัดการคู่ไม่ถูกต้อง');
    const {error}=await db.from('matching_pairs').update(changes).eq('id',pairId);if(error)return errResponse(error.message);
    await db.from('one_to_one_status_events').insert({round_id:String(row.round_id||'')||null,pair_id:pairId,event_type:eventType,actor_type:auth.isMC?'mc':'mentor',actor_ref:String(auth.role),metadata:{reason:reason||null,ownerRole:operation==='assign'?ownerRole:null,snoozedUntil:changes.care_snoozed_until||null}});
    return jsonResponse({ok:true,operation,changes});
  }

  if(action==='updateOneToOneScheduleOperation'){
    const pairId=String(p.pairId||''),scheduleId=String(p.scheduleId||''),operation=String(p.operation||''),reason=String(p.reason||'').trim().slice(0,500);const startsAt=new Date(String(p.startsAt||''));
    const {data:pair}=await db.from('matching_pairs').select('id,member_a:members!matching_pairs_member_a_id_fkey(id,mentor_team),member_b:members!matching_pairs_member_b_id_fkey(id,mentor_team)').eq('id',pairId).maybeSingle();const row=pair as Record<string,unknown>|null;if(!row||(!inScope(row.member_a as Record<string,unknown>)&&!inScope(row.member_b as Record<string,unknown>)))return errResponse('ไม่พบคู่ในขอบเขตที่คุณดูแล',403);
    const changes:Record<string,unknown>={change_reason:reason||null,changed_by:String(auth.role),updated_at:new Date().toISOString()};
    if(operation==='reschedule'){if(!Number.isFinite(startsAt.getTime())||startsAt<=new Date())return errResponse('กรุณาเลือกวันนัดใหม่ในอนาคต');changes.starts_at=startsAt.toISOString();changes.status='proposed';changes.confirmed_by_a_at=null;changes.confirmed_by_b_at=null;}
    else if(operation==='missed'){changes.status='missed';}
    else if(operation==='cancel'){changes.status='cancelled';}else return errResponse('คำสั่งนัดหมายไม่ถูกต้อง');
    const {error}=await db.from('one_to_one_schedules').update(changes).eq('id',scheduleId).eq('pair_id',pairId);if(error)return errResponse(error.message);const pairStatus=operation==='reschedule'?'scheduled':operation==='missed'?'missed_appointment':'matched';const {error:pairError}=await db.from('matching_pairs').update({status:pairStatus}).eq('id',pairId);if(pairError)return errResponse('อัปเดตนัดแล้ว แต่สถานะคู่ไม่สำเร็จ กรุณารีเฟรชและลองอีกครั้ง');await db.from('one_to_one_status_events').insert({pair_id:pairId,event_type:`schedule_${operation}`,actor_type:auth.isMC?'mc':'mentor',actor_ref:String(auth.role),metadata:{scheduleId,reason:reason||null,startsAt:changes.starts_at||null,pairStatus}});return jsonResponse({ok:true,operation,pairStatus});
  }

  if(action==='updateOneToOneReferralOutcome'){
    const id=String(p.id||''),stage=String(p.stage||''),notes=String(p.notes||'').trim().slice(0,1000),allowed=['connection_identified','permission_requested','permission_granted','introduction_sent','meeting_booked','referral_created','collaboration','won','not_ready','not_a_fit','learning_only'];if(!allowed.includes(stage))return errResponse('ขั้นผลลัพธ์ไม่ถูกต้อง');
    const {data:item}=await db.from('one_to_one_follow_up_actions').select('id,pair_id,owner:members!one_to_one_follow_up_actions_owner_member_id_fkey(id,mentor_team)').eq('id',id).maybeSingle();if(!item||!inScope((item as Record<string,unknown>).owner as Record<string,unknown>))return errResponse('ไม่พบรายการในขอบเขตที่คุณดูแล',403);
    const consentStages=['permission_granted','introduction_sent','meeting_booked','referral_created','won'];const changes={outcome_stage:stage,outcome:stage,outcome_notes:notes||null,outcome_updated_by:String(auth.role),consent_confirmed_at:consentStages.includes(stage)?new Date().toISOString():null,updated_at:new Date().toISOString(),status:['not_ready','not_a_fit','learning_only','won'].includes(stage)?'completed':'in_progress'};const {error}=await db.from('one_to_one_follow_up_actions').update(changes).eq('id',id);if(error)return errResponse(error.message);await db.from('one_to_one_status_events').insert({pair_id:String((item as Record<string,unknown>).pair_id),event_type:'referral_outcome_updated',actor_type:auth.isMC?'mc':'mentor',actor_ref:String(auth.role),metadata:{followUpId:id,stage}});return jsonResponse({ok:true,stage});
  }

  if(action==='getOneToOneOperationsDashboard'){
    const [{data:deliveries},{data:pairs},{data:schedules},{data:guided},{data:feedback},{data:followups},{data:attention}]=await Promise.all([
      db.from('line_message_deliveries').select('id,matching_pair_id,member_id,status,notification_type,sent_at,created_at,last_error,suppression_reason,message_payload,recipient_id').eq('module','one_to_one').order('created_at',{ascending:false}).limit(500),
      db.from('matching_pairs').select('id,status,created_at,member_a_id,member_b_id,member_a:members!matching_pairs_member_a_id_fkey(id,name,nickname,profession,company_name,mentor_team),member_b:members!matching_pairs_member_b_id_fkey(id,name,nickname,profession,company_name,mentor_team)').is('archived_at',null).order('created_at',{ascending:false}).limit(500),
      db.from('one_to_one_schedules').select('id,pair_id,status,starts_at').order('created_at',{ascending:false}).limit(500),
      db.from('guided_one_to_one_sessions').select('id,pair_id,status,completed_at').order('created_at',{ascending:false}).limit(500),
      db.from('one_to_one_feedback').select('id,pair_id,visibility,mentor_help,created_at').is('archived_at',null).order('created_at',{ascending:false}).limit(1000),
      db.from('one_to_one_follow_up_actions').select('id,pair_id,status,due_date,outcome_stage,outcome,updated_at').order('created_at',{ascending:false}).limit(1000),
      db.from('one_to_one_attention_items').select('id,pair_id,member_id,level,reason,status,assigned_role,due_date,snoozed_until,created_at,member:members(id,name,nickname,mentor_team)').in('status',['open','reviewed','in_progress','waiting_member','snoozed']).order('created_at',{ascending:false}).limit(300),
    ]);
    const scopedPairs=((pairs||[]) as Record<string,unknown>[]).filter(x=>inScope(x.member_a as Record<string,unknown>)||inScope(x.member_b as Record<string,unknown>)),pairIds=new Set(scopedPairs.map(x=>String(x.id))),scope=(rows:Record<string,unknown>[])=>(rows||[]).filter(x=>pairIds.has(String(x.pair_id||x.matching_pair_id)));
    const ds=scope((deliveries||[]) as Record<string,unknown>[]),ss=scope((schedules||[]) as Record<string,unknown>[]),gs=scope((guided||[]) as Record<string,unknown>[]),fb=scope((feedback||[]) as Record<string,unknown>[]),fu=scope((followups||[]) as Record<string,unknown>[]),at=((attention||[]) as Record<string,unknown>[]).filter(x=>inScope(x.member as Record<string,unknown>));
    const memberIds=[...new Set(scopedPairs.flatMap(x=>[String(x.member_a_id||''),String(x.member_b_id||'')]).filter(Boolean))],{data:profiles}=memberIds.length?await db.from('member_one_to_one_profiles').select('*').in('member_id',memberIds):{data:[]};const profileMap=new Map(((profiles||[]) as Record<string,unknown>[]).map(x=>[String(x.member_id),member121ProfileCompleteness(x)])),scheduleMap=new Map<string,Record<string,unknown>>();ss.forEach(x=>{const id=String(x.pair_id);if(!scheduleMap.has(id))scheduleMap.set(id,x);});const pairMap=new Map(scopedPairs.map(x=>[String(x.id),x]));
    const sentPairs=new Set(ds.filter(x=>x.status==='sent'&&x.notification_type==='weekly_121_matching').map(x=>String(x.matching_pair_id))),scheduledPairs=new Set(ss.filter(x=>!['cancelled','missed'].includes(String(x.status))).map(x=>String(x.pair_id))),sessionPairs=new Set(gs.filter(x=>['active','paused','completed'].includes(String(x.status))).map(x=>String(x.pair_id))),verifiedPairs=new Set(scopedPairs.filter(x=>['verified','late_verified'].includes(String(x.status))).map(x=>String(x.id))),reflectionPairs=new Set(fb.filter(x=>x.visibility==='shared').map(x=>String(x.pair_id))),followedPairs=new Set(fu.filter(x=>['completed'].includes(String(x.status))||Boolean(x.outcome_stage||x.outcome)).map(x=>String(x.pair_id)));
    const inbox=at.map(x=>({...x,pair:pairMap.get(String(x.pair_id))||null})),priorityWeight:Record<string,number>={urgent:0,waiting:1,normal:2},workQueue=scopedPairs.filter(x=>sentPairs.has(String(x.id))&&!verifiedPairs.has(String(x.id))).map(x=>{const id=String(x.id),status=String(x.status),schedule=scheduleMap.get(id)||null,ageDays=Math.max(0,Math.floor((Date.now()-new Date(String(x.created_at)).getTime())/86400000));return{...x,schedule,ageDays,profileCompleteness:{a:profileMap.get(String(x.member_a_id))||0,b:profileMap.get(String(x.member_b_id))||0},needsHelp:at.some(v=>String(v.pair_id)===id),priority:['unable_to_contact','missed_appointment','overdue'].includes(status)||ageDays>=3?'urgent':status==='partially_verified'?'waiting':'normal'};}).sort((a,b)=>(priorityWeight[String(a.priority)]??9)-(priorityWeight[String(b.priority)]??9)||Number(b.ageDays)-Number(a.ageDays));
    const overdueFollowUps=fu.filter(x=>['pending','in_progress','overdue'].includes(String(x.status))&&x.due_date&&new Date(String(x.due_date)+'T23:59:59')<new Date()).length;
    return jsonResponse({ok:true,permission:{scope:isSupport?'all_teams_support':auth.isMC?'chapter':'mentor_team',canContactMembers:!isSupport},funnel:{paired:scopedPairs.length,lineSent:sentPairs.size,scheduled:scheduledPairs.size,session:sessionPairs.size,verified:verifiedPairs.size,reflection:reflectionPairs.size,followUp:followedPairs.size},metrics:{sent:sentPairs.size,scheduled:scheduledPairs.size,waitingVerification:scopedPairs.filter(x=>['awaiting_verification','partially_verified'].includes(String(x.status))).length,completed:verifiedPairs.size,help:at.length,overdueFollowUps},mentorInbox:inbox,workQueue,referralPipeline:Object.fromEntries(['connection_identified','permission_requested','permission_granted','introduction_sent','meeting_booked','referral_created','collaboration','won','not_ready','not_a_fit','learning_only'].map(stage=>[stage,fu.filter(x=>String(x.outcome_stage||x.outcome)===stage).length])),notificationQueue:ds.filter(x=>['failed','skipped'].includes(String(x.status))).slice(0,100)});
  }

  if(action==='retryOneToOneDelivery'){
    if(!auth.isMC)return errResponse('เฉพาะ MC ที่ Retry ข้อความได้',403);if(!Boolean(p.confirmed))return errResponse('ต้องยืนยันก่อน Retry');const id=String(p.id||'');const {data:d}=await db.from('line_message_deliveries').select('id,status,recipient_id,member_id,message_payload,attempts').eq('id',id).eq('module','one_to_one').maybeSingle();const row=d as Record<string,unknown>|null;if(!row||row.status!=='failed')return errResponse('Retry ได้เฉพาะข้อความที่ส่งล้มเหลว');const messages=Array.isArray(row.message_payload)?row.message_payload:[];if(!messages.length)return errResponse('ข้อความเดิมไม่มี Payload สำหรับ Retry');const input={memberId:String(row.member_id||''),module:'one_to_one',category:'one_to_one_retry',priority:'action_required' as const},guard=await evaluateNotificationGuard(db,input);if(!guard.allowed)return jsonResponse({ok:false,suppressed:true,error:'ระบบระงับ Retry เพื่อป้องกันการรบกวนสมาชิก',reason:guard.reason},429);const result=await linePushMessages(String(row.recipient_id),messages as Parameters<typeof linePushMessages>[1],{db,idempotencyKey:`121:retry:${id}:${Number(row.attempts||0)+1}`,memberId:String(row.member_id||''),notificationType:'one_to_one_retry',source:'api/mentor-121'});return jsonResponse({ok:true,skipped:Boolean(result.skipped),deliveryId:result.deliveryId});
  }

  if(action==='getMentorOneToOneCare'){
    const [{data:attention},{data:pairs},{data:followUps},{data:feedback}]=await Promise.all([
      db.from('one_to_one_attention_items').select('id,pair_id,member_id,level,reason,evidence,suggested_action,status,due_date,created_at,assigned_role,member:members(id,name,nickname,mentor_team)').in('status',['open','reviewed','in_progress','waiting_member','snoozed']).order('created_at',{ascending:false}).limit(200),
      db.from('matching_pairs').select('id,status,created_at,member_a_id,member_b_id,round:matching_rounds(meeting_date,ends_at),member_a:members!matching_pairs_member_a_id_fkey(id,name,nickname,mentor_team),member_b:members!matching_pairs_member_b_id_fkey(id,name,nickname,mentor_team),schedules:one_to_one_schedules(id,starts_at,status)').in('status',[...activeStatuses,'verified','late_verified']).is('archived_at',null).order('created_at',{ascending:false}).limit(200),
      db.from('one_to_one_follow_up_actions').select('id,pair_id,action_type,description,due_date,status,owner:members!one_to_one_follow_up_actions_owner_member_id_fkey(id,name,nickname,mentor_team),related:members!one_to_one_follow_up_actions_related_member_id_fkey(id,name,nickname)').in('status',['pending','in_progress','overdue']).order('due_date',{ascending:true}).limit(200),
      db.from('one_to_one_feedback').select('id,pair_id,respondent_member_id,outcomes,next_action_type,next_action_detail,created_at,respondent:members!one_to_one_feedback_respondent_member_id_fkey(id,name,nickname,mentor_team),about:members!one_to_one_feedback_about_member_id_fkey(id,name,nickname,profession,company_name)').eq('visibility','shared').is('archived_at',null).order('created_at',{ascending:false}).limit(200),
    ]);
    const scopedAttention=((attention||[]) as Record<string,unknown>[]).filter(x=>inScope(x.member as Record<string,unknown>));
    const scopedAllPairs=((pairs||[]) as Record<string,unknown>[]).filter(x=>inScope(x.member_a as Record<string,unknown>)||inScope(x.member_b as Record<string,unknown>)),scopedPairs=scopedAllPairs.filter(x=>activeStatuses.includes(String(x.status)));
    const scopedFollowUps=((followUps||[]) as Record<string,unknown>[]).filter(x=>inScope(x.owner as Record<string,unknown>));
    const scopedFeedback=((feedback||[]) as Record<string,unknown>[]).filter(x=>inScope(x.respondent as Record<string,unknown>));
    const now=Date.now(),stalled=scopedPairs.filter(x=>now-new Date(String(x.created_at)).getTime()>3*86400000&&!['confirmed_schedule','partially_verified'].includes(String(x.status))).length;
    const referralOpportunities=scopedFeedback.filter(x=>Array.isArray(x.outcomes)&&(x.outcomes as unknown[]).some(v=>['referral_opportunity','collaboration','connection'].includes(String(v)))||String(x.next_action_type||'')==='introduce');
    return jsonResponse({ok:true,team:isSupport?'ทุกทีม':team||'ทุกทีม',permission:{scope:isSupport?'all_teams_support':auth.isMC?'chapter':'mentor_team',canContactMembers:!isSupport},attention:scopedAttention,pairs:scopedPairs,followUps:scopedFollowUps,referralOpportunities,stats:{attention:scopedAttention.length,active:scopedPairs.length,stalled,followUp:scopedFollowUps.length,referrals:referralOpportunities.length,completed:scopedAllPairs.filter(x=>['verified','late_verified'].includes(String(x.status))).length}});
  }

  if(action==='updateMentorOneToOneCare'){
    const id=String(p.id||''),requestedStatus=String(p.status||''),resolution=String(p.resolution||'').trim().slice(0,1000);if(!['reviewed','in_progress','waiting_member','snoozed','resolved','no_action_required','escalated'].includes(requestedStatus))return errResponse('สถานะไม่ถูกต้อง');const {data:item}=await db.from('one_to_one_attention_items').select('id,pair_id,member_id,reason,member:members(id,name,nickname,mentor_team)').eq('id',id).maybeSingle();if(!item||!inScope((item as Record<string,unknown>).member as Record<string,unknown>))return errResponse('ไม่พบรายการในทีมของคุณ',403);const now=new Date(),status=requestedStatus==='escalated'?'reviewed':requestedStatus,changes:Record<string,unknown>={status,assigned_role:requestedStatus==='escalated'?'mc':String(p.assignedRole||auth.role),resolution:resolution||null,updated_at:now.toISOString()};if(status==='snoozed')changes.snoozed_until=String(p.snoozedUntil||new Date(now.getTime()+86400000).toISOString());if(['resolved','no_action_required'].includes(status))changes.resolved_at=now.toISOString();const {error}=await db.from('one_to_one_attention_items').update(changes).eq('id',id);if(error)return errResponse(error.message);const member=(item as Record<string,unknown>).member as Record<string,unknown>;await db.from('mentor_logs').insert({member_id:String((item as Record<string,unknown>).member_id),mentor_team:String(member.mentor_team||team),session_date:now.toISOString().slice(0,10),notes:`1-2-1 Care · ${requestedStatus}`,next_actions:resolution||'อัปเดตจาก Mobile Mentor'});if(requestedStatus==='escalated')await db.from('notifications').insert({type:'one_to_one_escalated_to_mc',severity:'warning',title:`Mentor ทีม ${team} ส่งต่อเคส 1-2-1`,body:resolution||String((item as Record<string,unknown>).reason||''),data:{attentionId:id,pairId:(item as Record<string,unknown>).pair_id,memberId:(item as Record<string,unknown>).member_id},target_audience:['role:mc']});await db.from('one_to_one_status_events').insert({pair_id:String((item as Record<string,unknown>).pair_id||'')||null,member_id:String((item as Record<string,unknown>).member_id),event_type:'mentor_care_updated',actor_type:'mentor',actor_ref:String(auth.role),metadata:{attentionId:id,status:requestedStatus,resolution}});return jsonResponse({ok:true,status:requestedStatus});
  }

  if(action==='remindMentorOneToOneMember'){
    const pairId=String(p.pairId||''),memberId=String(p.memberId||''),dryRun=p.dryRun!==false,confirmed=Boolean(p.confirmed);const {data:member}=await db.from('members').select('id,name,nickname,mentor_team').eq('id',memberId).maybeSingle();if(!member||!inScope(member as Record<string,unknown>))return errResponse('สมาชิกไม่ได้อยู่ในทีมของคุณ',403);const {data:pair}=await db.from('matching_pairs').select('id,member_a_id,member_b_id,status').eq('id',pairId).maybeSingle();if(!pair||![String((pair as Record<string,unknown>).member_a_id),String((pair as Record<string,unknown>).member_b_id)].includes(memberId))return errResponse('ไม่พบคู่ที่เลือก');if(['verified','late_verified','cancelled'].includes(String((pair as Record<string,unknown>).status)))return errResponse('คู่นี้ปิดขั้นตอนแล้ว ไม่จำเป็นต้องส่งเตือน');const {data:link}=await db.from('line_members').select('line_user_id').eq('member_id',memberId).maybeSingle();const lineId=String((link as Record<string,unknown>|null)?.line_user_id||'');if(!lineId)return errResponse('สมาชิกยังไม่เชื่อม LINE');const message=String(p.customMessage||'').trim().slice(0,5000)||'🤝 Mentor ขอชวนให้คุณดำเนินการ 1-2-1 ต่อครับ\nเปิด MY121 เพื่อดูคู่ เลือกเวลา หรือยืนยันขั้นตอนล่าสุด';const input={memberId,module:'one_to_one',category:'one_to_one_mentor_reminder',priority:'reminder' as const},guard=await evaluateNotificationGuard(db,input),key=`121:mentor-remind:${pairId}:${memberId}:${new Date().toISOString().slice(0,10)}`;if(dryRun)return jsonResponse({ok:true,dryRun:true,message,audience:String((member as Record<string,unknown>).nickname||(member as Record<string,unknown>).name||'สมาชิก'),allowed:guard.allowed,reason:guard.reason||null});if(!confirmed)return errResponse('ต้องตรวจข้อความและยืนยันก่อนส่ง LINE');if(!guard.allowed){await logSuppressedNotification(db,input,guard,key,lineId);return jsonResponse({ok:false,suppressed:true,error:'ระบบยังไม่ส่งข้อความ เพื่อป้องกันการรบกวนสมาชิก',reason:guard.reason,guard},429);}const result=await linePush(lineId,message,{db,idempotencyKey:key,memberId,notificationType:'one_to_one_mentor_reminder',source:'api/mentor-121'});await db.from('one_to_one_status_events').insert({pair_id:pairId,member_id:memberId,event_type:'mentor_reminder_sent',actor_type:'mentor',actor_ref:String(auth.role),metadata:{deliveryId:result.deliveryId||null,skipped:Boolean(result.skipped)}});return jsonResponse({ok:true,skipped:Boolean(result.skipped),guard});
  }

  if(action==='reissueMentorOneToOneCode'){
    const pairId=String(p.pairId||''),memberId=String(p.memberId||'');const {data:member}=await db.from('members').select('id,name,nickname,mentor_team').eq('id',memberId).maybeSingle();if(!member||!inScope(member as Record<string,unknown>))return errResponse('สมาชิกไม่ได้อยู่ในทีมของคุณ',403);const {data:pair}=await db.from('matching_pairs').select('id,round_id,member_a_id,member_b_id,status').eq('id',pairId).maybeSingle();if(!pair||![String((pair as Record<string,unknown>).member_a_id),String((pair as Record<string,unknown>).member_b_id)].includes(memberId))return errResponse('ไม่พบคู่ที่เลือก');if(['verified','late_verified'].includes(String((pair as Record<string,unknown>).status)))return errResponse('คู่นี้ยืนยันเสร็จแล้ว');const pepper=Deno.env.get('ONE_TO_ONE_CODE_PEPPER')||'';if(!pepper)return errResponse('ระบบรหัสยังไม่ได้ตั้งค่า',503);const code=generateHandshakeCode(),expiresAt=new Date(Date.now()+86400000).toISOString(),hash=await handshakeCodeHash(pairId,memberId,code,pepper);const {data:old}=await db.from('one_to_one_verifications').select('verified_partner_code_at').eq('pair_id',pairId).eq('member_id',memberId).maybeSingle();const {error}=await db.from('one_to_one_verifications').upsert({pair_id:pairId,member_id:memberId,code_hash:hash,code_expires_at:expiresAt,attempts:0,flow_started_at:new Date().toISOString(),verified_partner_code_at:(old as Record<string,unknown>|null)?.verified_partner_code_at||null,locked_until:null},{onConflict:'pair_id,member_id'});if(error)return errResponse(error.message);await db.from('one_to_one_status_events').insert({round_id:String((pair as Record<string,unknown>).round_id),pair_id:pairId,member_id:memberId,event_type:'verification_code_reissued',actor_type:'mentor',actor_ref:String(auth.role),metadata:{expiresAt}});return jsonResponse({ok:true,code,expiresAt});
  }

  if(action==='getMentorOneToOneMemberTimeline'){
    const memberId=String(p.memberId||'');const {data:member}=await db.from('members').select('id,name,nickname,mentor_team').eq('id',memberId).maybeSingle();if(!member||!inScope(member as Record<string,unknown>))return errResponse('สมาชิกไม่ได้อยู่ในทีมของคุณ',403);const {data:pairs}=await db.from('matching_pairs').select('id,status,created_at,member_a_id,member_b_id,round:matching_rounds(meeting_date),schedules:one_to_one_schedules(id,starts_at,status),followups:one_to_one_follow_up_actions(id,description,due_date,status),guided:guided_one_to_one_sessions(id,session_mode,status,duration_seconds,completed_at,shared_content)').or(`member_a_id.eq.${memberId},member_b_id.eq.${memberId}`).order('created_at',{ascending:false}).limit(50);const rows=(pairs||[]) as Record<string,unknown>[],partnerIds=[...new Set(rows.map(x=>String(x.member_a_id)===memberId?String(x.member_b_id):String(x.member_a_id)))];const {data:partners}=partnerIds.length?await db.from('members').select('id,name,nickname,profession,company_name').in('id',partnerIds):{data:[]};const sessionIds=rows.flatMap(x=>Array.isArray(x.guided)?x.guided as Record<string,unknown>[]:x.guided?[x.guided as Record<string,unknown>]:[]).map(x=>String(x.id));const {data:triggers}=sessionIds.length?await db.from('guided_referral_triggers').select('id,session_id,owner_member_id,trigger_text,context,priority').in('session_id',sessionIds).eq('owner_approved',true).eq('is_active',true).is('archived_at',null):{data:[]};const map=new Map(((partners||[]) as Record<string,unknown>[]).map(x=>[String(x.id),x]));return jsonResponse({ok:true,member,timeline:rows.map(x=>{const guided=Array.isArray(x.guided)?(x.guided as Record<string,unknown>[])[0]||null:x.guided as Record<string,unknown>|null;return{...x,partner:map.get(String(x.member_a_id)===memberId?String(x.member_b_id):String(x.member_a_id))||null,guided:guided?{...guided,referralTriggers:((triggers||[]) as Record<string,unknown>[]).filter(t=>String(t.session_id)===String(guided.id))}:null};}),stats:{total:rows.length,completed:rows.filter(x=>['verified','late_verified'].includes(String(x.status))).length,pending:rows.filter(x=>activeStatuses.includes(String(x.status))).length}});
  }
  return errResponse(`Unknown mentor 1-2-1 action: ${action}`);
}
