-- Growth Mobile 2.2: retry-safe operational actions per Chapter.
ALTER TABLE public.growth_tasks
  ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_growth_tasks_chapter_idempotency
  ON public.growth_tasks(chapter_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

COMMENT ON COLUMN public.growth_tasks.idempotency_key IS
  'Optional retry key for Chapter-scoped Growth actions; generated by the workflow, never used for authorization.';
